name: Build

on:
 push:
  branches:
  - 'master'
  - 'develop'
  - 'github-action'

jobs:
 Build:
  runs-on: windows-2019
  steps:

#  - name: Install Windows XP Support for Visual Studio 2022 # windows-2022 # v141_xp # Installation takes more than 5 minutes
#    run: |
#         Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
#         $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
#         $componentsToAdd = @(
#           "Microsoft.VisualStudio.Component.WinXP"
#         )
#         [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
#         $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
#         $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
#         if ($process.ExitCode -eq 0)
#         {
#           Write-Host "components have been successfully added"
#           Get-ChildItem C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.Windows.XPSupport.*
#         }
#         else
#         {
#           Write-Host "components were not installed"
#           exit 1
#         }

  - name: Clone cnc-ddraw
    uses: actions/checkout@v4

  - name: Release build
    id: build-release
    uses: ./
    with:
     release: true

  - name: ReleaseWin2000 build
    id: build-releasewin2000
    uses: ./
    with:
     releasewin2000: true

  - name: Debug build
    id: build-debug
    uses: ./
    with:
     debug: true

  - name: DebugLog build
    id: build-debuglog
    uses: ./
    with:
     debuglog: true

  - name: DebugLogMini build
    id: build-debuglogmini
    uses: ./
    with:
     debuglogmini: true

  - name: Release build config
    id: build-releaseconfig
    uses: ./
    with:
     releaseconfig: true

  - name: Debug build config
    id: build-debugconfig
    uses: ./
    with:
     debugconfig: true

  - name:  Prepare artifact
    run:   |
           :

           mkdir -p cnc-ddraw-release
           mkdir -p cnc-ddraw-release-pdb
           mkdir -p cnc-ddraw-releasewin2000
           mkdir -p cnc-ddraw-releasewin2000-pdb
           mkdir -p cnc-ddraw-debug
           mkdir -p cnc-ddraw-debuglog
           mkdir -p cnc-ddraw-debuglogmini
           #mkdir -p cnc-ddraw-releaseconfig-pdb
           mkdir -p cnc-ddraw-debugconfig

           curl -o "glsl-shaders-master.zip" "https://codeload.github.com/libretro/glsl-shaders/zip/refs/heads/master"
           7z x "glsl-shaders-master.zip"
           cp -r glsl-shaders-master cnc-ddraw-release/Shaders
           cp -r glsl-shaders-master cnc-ddraw-releasewin2000/Shaders

           cp "${{ steps.build-release.outputs.release }}" cnc-ddraw-release
           cp "${{ steps.build-releaseconfig.outputs.releaseconfig }}" cnc-ddraw-release
           cp LICENSE cnc-ddraw-release/LICENSE.txt
           cp README.md cnc-ddraw-release/README.txt
           "./cnc-ddraw-release/cnc-ddraw config.exe" -restart &

           cp "${{ steps.build-release.outputs.release-pdb }}" cnc-ddraw-release-pdb

           cp "${{ steps.build-releasewin2000.outputs.releasewin2000 }}" cnc-ddraw-releasewin2000
           cp "${{ steps.build-releaseconfig.outputs.releaseconfig }}" cnc-ddraw-releasewin2000
           cp LICENSE cnc-ddraw-releasewin2000/LICENSE.txt
           cp README.md cnc-ddraw-releasewin2000/README.txt
           "./cnc-ddraw-releasewin2000/cnc-ddraw config.exe" -restart &

           cp "${{ steps.build-releasewin2000.outputs.releasewin2000-pdb }}" cnc-ddraw-releasewin2000-pdb

           cp "${{ steps.build-debug.outputs.debug }}" cnc-ddraw-debug
           cp "${{ steps.build-debug.outputs.debug-pdb }}" cnc-ddraw-debug

           cp "${{ steps.build-debuglog.outputs.debuglog }}" cnc-ddraw-debuglog
           cp "${{ steps.build-debuglog.outputs.debuglog-pdb }}" cnc-ddraw-debuglog

           cp "${{ steps.build-debuglogmini.outputs.debuglogmini }}" cnc-ddraw-debuglogmini
           cp "${{ steps.build-debuglogmini.outputs.debuglogmini-pdb }}" cnc-ddraw-debuglogmini

           #cp "${{ steps.build-releaseconfig.outputs.releaseconfig-pdb }}" cnc-ddraw-releaseconfig-pdb

           cp "${{ steps.build-debugconfig.outputs.debugconfig }}" cnc-ddraw-debugconfig
           #cp "${{ steps.build-debugconfig.outputs.debugconfig-pdb }}" cnc-ddraw-debugconfig

    shell: bash

  - name: Upload artifacts cnc-ddraw-release
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-release
     path: cnc-ddraw-release
     retention-days: 14

  - name: Upload artifacts cnc-ddraw-release-pdb
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-release-pdb
     path: cnc-ddraw-release-pdb
     retention-days: 14

  - name: Upload artifacts cnc-ddraw-releasewin2000
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-releasewin2000
     path: cnc-ddraw-releasewin2000
     retention-days: 14

  - name: Upload artifacts cnc-ddraw-releasewin2000-pdb
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-releasewin2000-pdb
     path: cnc-ddraw-releasewin2000-pdb
     retention-days: 14

  - name: Upload artifacts cnc-ddraw-debug
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-debug
     path: cnc-ddraw-debug
     retention-days: 14

  - name: Upload artifacts cnc-ddraw-debuglog
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-debuglog
     path: cnc-ddraw-debuglog
     retention-days: 14

  - name: Upload artifacts cnc-ddraw-debuglogmini
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-debuglogmini
     path: cnc-ddraw-debuglogmini
     retention-days: 14

#  - name: Upload artifacts cnc-ddraw-releaseconfig-pdb
#    uses: actions/upload-artifact@v4
#    with:
#     name: cnc-ddraw-releaseconfig-pdb
#     path: cnc-ddraw-releaseconfig-pdb
#     retention-days: 14

  - name: Upload artifacts cnc-ddraw-debugconfig
    uses: actions/upload-artifact@v4
    with:
     name: cnc-ddraw-debugconfig
     path: cnc-ddraw-debugconfig
     retention-days: 14
